name: CI

on:
  push:
    branches:
      - main
      - master
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 5
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ['16', '18']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm prepare
      - run: pnpm lint
      - run: pnpm test
